export const ERROR_MESSAGES = {
    INVALID_CREDENTIALS: "Invalid email or password",
    USER_NOT_FOUND: "User not found",
    USER_ALREADY_EXISTS: "User with this email already exists",
    EMAIL_ALREADY_EXISTS: "Email is already registered",
    USERNAME_ALREADY_EXISTS: "Username is already taken",
    INVALID_TOKEN: "Invalid or expired token",
    UNAUTHORIZED: "You are not authorized to perform this action",
    FORBIDDEN: "Access denied",
    SERVER_ERROR: "Something went wrong. Please try again later",
    VALIDATION_ERROR: "Please fill in all required fields correctly",
    FILE_UPLOAD_ERROR: "There was a problem uploading the file",
    PASSWORD_MISMATCH: "Passwords do not match",
    PASSWORD_TOO_WEAK: "Password must be at least 6 characters",
    ACCOUNT_DEACTIVATED: "Your account has been deactivated",
    ACCOUNT_NOT_VERIFIED: "Please verify your email before proceeding",
    BOOKING_FAILED: "Failed to book the service",
    CATEGORY_EXISTS: "This category already exists",
    CATEGORY_NOT_FOUND: "Category not found",
    VENDOR_NOT_FOUND: "Vendor not found",
    MESSAGE_FAILED: "Failed to send message",
    AI_RECOMMENDATION_FAILED: "Failed to generate AI recommendations",
    INVALID_INPUT: "Invalid input data",
    MISSING_FIELDS: "Required fields are missing",
    DATABASE_CONNECTION_FAILED: "Failed to connect to the database",
    ACTION_FAILED: "Action could not be completed",
    RATE_LIMITED: "Too many requests. Please try again later",    TOKEN_EXPIRED: "Verification code has expired. Click resend to get a new code",
    EMAIL_VERIFICATION: 'Error sending verification email',
    ACCOUNT_ALREADY_VERIFIED: 'This account is already verified'
  };

  

  export const SUCCESS_MESSAGES = {
    USER_REGISTERED: "User has been registered successfully",
    USER_LOGIN: "User logged in successfully",
    USER_DETAIL_UPDATED: "User has been updated successfully",
    USER_AVATAR_UPDATED: "User avatar has been updated successfully",
    FILE_UPLOADED: "File has been uploaded successfully",
    PASSWORD_UPDATED: "Password has been updated successfully",
    EMAIL_UPDATED: "Email has been updated successfully",
    USERNAME_UPDATED: "Username has been updated successfully",
    REFRESH_TOKEN_UPDATED: "Refresh Token has been updated successfully",
    CURRENT_USER: "User has been updated successfully",
    USER_LOGOUT: "User logged out successfully",
    DELETE_USER: "User account has been deleted successfully",
    DEACTIVATE_USER: "User account has been deactivated successfully",
    ACTIVATE_USER: "User account has been activated successfully",
    EMAIL_VERIFIED: "Email verified successfully",
    EMAIL_VERIFICATION_SEND: "Verification email send successfully",
  
    PROFILE_UPDATED: "Profile updated successfully",
    BOOKING_CONFIRMED: "Booking confirmed successfully",
    MESSAGE_SENT: "Message sent successfully",
    CATEGORY_CREATED: "Vendor category created successfully",
    VENDOR_ADDED: "Vendor registered successfully",
    AI_RECOMMENDATION_SUCCESS: "AI recommendations generated",
  };
  